# Generated by Django 5.1.2 on 2024-10-27 22:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_recipes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmediacontact',
            name='phone_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(7)]),
        ),
    ]
