# Generated by Django 5.1.2 on 2024-10-28 04:50

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_alter_socialmediacontact_phone_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'O нас',
                'verbose_name_plural': 'О нас',
            },
        ),
        migrations.RemoveField(
            model_name='recipes',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='recipes',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='market.productcategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='recipes',
            field=models.ManyToManyField(related_name='products', to='market.recipes'),
        ),
        migrations.AlterField(
            model_name='socialmediacontact',
            name='phone_number',
            field=models.URLField(),
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Публикация',
                'verbose_name_plural': 'Публикации',
                'ordering': ['-created_at'],
            },
        ),
    ]
