# Generated by Django 5.1.2 on 2024-10-28 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_aboutme_remove_recipes_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='recipes',
        ),
    ]
