# Generated by Django 5.1.2 on 2024-10-28 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_remove_product_recipes'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='categories',
            field=models.ManyToManyField(related_name='recipes', to='market.productcategory'),
        ),
    ]
