# Generated by Django 5.1.2 on 2024-10-28 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_aboutme_name_alter_aboutme_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
