# Generated by Django 5.1.2 on 2024-10-28 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0011_alter_aboutme_image_alter_aboutme_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='author',
        ),
    ]
