# Generated by Django 5.1.2 on 2024-10-28 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0012_remove_publication_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='image',
            field=models.ImageField(default=1, upload_to='publications/'),
            preserve_default=False,
        ),
    ]
