# Generated by Django 5.1.2 on 2024-10-28 10:08

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0013_publication_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='content_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='content_ru',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='content_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='name_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='recipes',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='recipes',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='recipes',
            name='name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='recipes',
            name='name_ru',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
