# Generated by Django 5.1.2 on 2024-10-28 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0014_aboutme_content_en_aboutme_content_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='name_ru',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
