# Generated by Django 5.1.2 on 2024-10-29 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0015_aboutme_name_en_aboutme_name_ru'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='market.product'),
            preserve_default=False,
        ),
    ]
