# Generated by Django 5.1.2 on 2024-10-29 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0019_rename_instructions_recipes_directions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='directions',
            field=models.CharField(max_length=200),
        ),
    ]
