# Generated by Django 5.1.2 on 2024-10-30 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0020_alter_recipes_directions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='directions',
            field=models.TextField(),
        ),
    ]
